manifest:
  remotes:
    - name: nrfcloud
      url-base: https://github.com/nRFCloud
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: origin
      url-base: https://github.com/plskeggs
  projects:
    - name: sdk-nrf
      path: nrf
      remote: origin
      revision: Branch_ncs-2.7.0-feature-fix-ble-fota
      #remote: nordic
      #revision: pull/8960/head
      import: true
  self:
    path: lte-gateway
